Attribute VB_Name = "XPStyles"
Option Explicit

'----------------------------------------
'   XPStyles.bas
'----------------------------------------
'   generated by:
'      XP Style Manifest Resource Maker
'
'   How to use:
'   Just add this module to your project
'   and call InitXPStyles on your app
'   load.
'   Function InitXPStyles will return:
'       - True  [ if everything is ok! ]
'       - False [ if some error occurs ]
'----------------------------------------
' pulled down from vbAccelerator.com
'----------------------------------------
Private Declare Function InitCommonControlsEx Lib "comctl32.dll" (ByRef TLPINITCOMMONCONTROLSEX As tagInitCommonControlsEx) As Long

Private Type tagInitCommonControlsEx
    dwSize  As Long 'size of this structure
    dwICC   As Long 'flags indicating which classes to be initialized
End Type

Private Const ICC_USEREX_CLASSES = &H200

Public Function InitXPStyles() As Boolean

    On Error Resume Next

    Dim iccex As tagInitCommonControlsEx

    ' Ensure CC available:
    iccex.dwSize = LenB(iccex)
    iccex.dwICC = ICC_USEREX_CLASSES
    
    InitXPStyles = InitCommonControlsEx(iccex)
    
    On Error GoTo 0

End Function
